### ISSUE TITLE
Canceling a meal

### ISSUE THREAD

**Issue by Reprazent** [Reprazent/mealz#5]
Meals should become canceled:
- [x] Save a canceled_at date
- [x] Recalculate the balance for all users
- [x] Delete wrongly created users (if the user has no mealz left after deleting)

```
m.users.each do |eater|
  eater.balance -= m.amount if eater == m.payed_by
  eater.balance += m.amount / m.users.count
  eater.save!
end
```

This could go in a new seperate MealDestroyer

**Comment by pjaspers** [comment]
Thanks @lewis-fidlers!

**Comment by lewis-fidlers** [comment]
![h5](https://media4.giphy.com/media/l2Sqdb0SoKNY8RLry/200.gif#5)
